USE recycling_db;


INSERT INTO candidates (name, experience, skills) VALUES 
("Dr. Antonia Tromp", 14, "Team Leadership, Lean Six Sigma, Waste Management"),
("Brandon Murazik", 9, "Team Leadership, Circular Economy, Safety Compliance"),
("Adam Batz", 5, "Safety Compliance, Lean Six Sigma, Circular Economy"),
("Dr. Wallace Cummerata", 10, "Team Leadership, Circular Economy, Waste Management"),
("Duane Bradtke", 8, "Lean Six Sigma, Waste Management, Circular Economy"),
("Laura Monahan", 14, "Team Leadership, Circular Economy, Lean Six Sigma"),
("Miss Sabrina Wilkinson", 3, "Waste Management, Safety Compliance, Circular Economy"),
("Peter Gleason", 11, "Circular Economy, Waste Management, Team Leadership"),
("Edgar Weimann", 7, "Lean Six Sigma, Team Leadership, Circular Economy"),
("Mr. Dewey Green", 6, "Team Leadership, Waste Management, Safety Compliance"),
("Rosemary Brown", 20, "Team Leadership, Waste Management, Safety Compliance"),
("Jody Yost", 18, "Circular Economy, Lean Six Sigma, Team Leadership"),
("Noah Altenwerth", 17, "Waste Management, Safety Compliance, Lean Six Sigma"),
("Holly Sauer", 6, "Team Leadership, Circular Economy, Lean Six Sigma"),
("Maureen Runte", 10, "Waste Management, Safety Compliance, Team Leadership"),
("Matt Prohaska", 11, "Waste Management, Circular Economy, Lean Six Sigma"),
("Willis Sauer", 12, "Lean Six Sigma, Safety Compliance, Circular Economy"),
("Darren Kris", 2, "Lean Six Sigma, Safety Compliance, Team Leadership"),
("Jimmie Vandervort", 2, "Circular Economy, Lean Six Sigma, Safety Compliance"),
("Travis Crist-Hudson Sr.", 9, "Safety Compliance, Team Leadership, Circular Economy"),
("Ricardo O'Kon", 7, "Circular Economy, Team Leadership, Waste Management"),
("May Schmeler", 7, "Circular Economy, Waste Management, Lean Six Sigma"),
("Felix Batz", 3, "Lean Six Sigma, Waste Management, Team Leadership"),
("Andrew Rutherford", 16, "Circular Economy, Lean Six Sigma, Team Leadership"),
("Dr. Cora Fisher", 11, "Circular Economy, Waste Management, Safety Compliance"),
("Fredrick Grimes V", 5, "Team Leadership, Lean Six Sigma, Waste Management"),
("Estelle Schneider", 19, "Waste Management, Safety Compliance, Team Leadership"),
("June Pagac", 12, "Safety Compliance, Circular Economy, Team Leadership"),
("Victor Anderson IV", 8, "Team Leadership, Lean Six Sigma, Safety Compliance"),
("Herbert Keeling", 11, "Team Leadership, Safety Compliance, Lean Six Sigma"),
("Faye Krajcik", 13, "Waste Management, Safety Compliance, Lean Six Sigma"),
("Velma Bartell", 2, "Lean Six Sigma, Team Leadership, Waste Management"),
("Mr. Joe Wisoky", 13, "Team Leadership, Circular Economy, Lean Six Sigma"),
("Marcia Daniel", 17, "Team Leadership, Waste Management, Lean Six Sigma"),
("Arthur Littel", 17, "Waste Management, Circular Economy, Lean Six Sigma"),
("Derek Kuhn", 10, "Waste Management, Circular Economy, Team Leadership"),
("Jody Mertz", 3, "Lean Six Sigma, Team Leadership, Safety Compliance"),
("Peter Reilly", 13, "Team Leadership, Waste Management, Safety Compliance"),
("Shawna White", 13, "Safety Compliance, Lean Six Sigma, Team Leadership"),
("Israel Mayer", 3, "Team Leadership, Safety Compliance, Lean Six Sigma");


INSERT INTO evaluations (candidate_id, crisis_score, sustainability_score, motivation_score) VALUES 
(1, 88, 92, 95), (2, 76, 84, 82), (3, 65, 78, 70), (4, 82, 89, 85), 
(5, 74, 81, 68), (6, 90, 95, 92), (7, 55, 72, 64), (8, 79, 87, 83), 
(9, 72, 80, 88), (10, 68, 75, 81), (11, 96, 91, 98), (12, 93, 94, 90), 
(13, 89, 85, 87), (14, 70, 82, 79), (15, 77, 79, 84), (16, 81, 90, 72), 
(17, 84, 88, 75), (18, 45, 60, 78), (19, 48, 65, 62), (20, 78, 85, 89), 
(21, 75, 83, 80), (22, 72, 88, 65), (23, 58, 68, 75), (24, 91, 94, 93), 
(25, 80, 91, 77), (26, 64, 70, 82), (27, 95, 88, 97), (28, 82, 85, 90), 
(29, 73, 75, 85), (30, 81, 78, 89), (31, 87, 82, 84), (32, 50, 62, 75), 
(33, 86, 92, 88), (34, 92, 87, 94), (35, 88, 93, 85), (36, 78, 89, 82), 
(37, 56, 65, 79), (38, 85, 80, 91), (39, 84, 78, 92), (40, 52, 60, 82);